# coding: utf-8
gem 'cocoapods', '1.9.3'

platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks! :linkage => :static

install! 'cocoapods',
    :incremental_installation => true,
    :generate_multiple_pod_projects => true,
    :warn_for_multiple_pod_sources => false

target 'EnumHashCrash' do
  pod 'FooA', :path => './FooA'
end

pre_install do |installer|
  installer.pod_targets.each do |pod_target|
    attributes_hash = pod_target.root_spec.attributes_hash
    pod_target_xcconfig = (attributes_hash['pod_target_xcconfig'] ||= {})

    # pod_target_xcconfig['SWIFT_VERSION'] = '5.3'
    # pod_target_xcconfig['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    pod_target_xcconfig['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
  end
end
